namespace MinimalTextEditorLite.Core.Rendering;

public interface IPdfRenderer
{
    /// <summary>
    /// Renders a complete HTML document into a PDF file and returns the generated bytes.
    /// The concrete implementation lives outside the Core project because WebView2/WPF
    /// are Windows-specific UI dependencies.
    /// </summary>
    /// <param name="html">Complete HTML document, including html, head and body tags.</param>
    /// <param name="options">PDF rendering and print settings.</param>
    /// <returns>The generated PDF bytes.</returns>
    Task<byte[]> RenderHtmlToPdfAsync(string html, PdfRenderOptions options);
}
